{
    "name": "Five Death Star",
    "description": "5人向け",
    "creator": "rauruca",
    "version": "1.0.0",
    "planets": [
        {
            "name": "Erhe",
            "mass": 50000,
            "position_x": 7056.54052734375,
            "position_y": 18259.93359375,
            "velocity_x": -149.0727081298828,
            "velocity_y": 57.609046936035156,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 528226176,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Death Star 2",
            "mass": 20000,
            "position_x": 5031.8564453125,
            "position_y": 15893.3603515625,
            "velocity_x": 66.21076965332031,
            "velocity_y": -126.57328033447266,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 438742848,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Death Star 3",
            "mass": 35000,
            "position_x": 6427.85986328125,
            "position_y": 22442.607421875,
            "velocity_x": 91.34487915039062,
            "velocity_y": 93.7452392578125,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 134401760,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Death Star 4",
            "mass": 35000,
            "position_x": 2100.4736328125,
            "position_y": 20301.357421875,
            "velocity_x": -66.81978607177734,
            "velocity_y": 257.2986145019531,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1480322432,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        },
        {
            "name": "Death Star 5",
            "mass": 35000,
            "position_x": 13430.2275390625,
            "position_y": 17016.49609375,
            "velocity_x": -186.64268493652344,
            "velocity_y": -134.96945190429688,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 898876928,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 0,
                "heightAdjustments": []
            }
        }
    ]
}